version: 2
jobs:
  build:
    working_directory: ~/wayback-discover-diff
    docker:
      - image: circleci/python:3.5
    steps:
      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            python setup.py install

      - run:
          name: Tests
          command: |
            . venv/bin/activate
            coverage run run_tests.py -v web_monitoring/tests/
      - run:
          name: Coverage
          command: |
            . venv/bin/activate
            coverage report -m
      - run:
          name: Code linting
          command: |
            . venv/bin/activate
            pyflakes web_monitoring

workflows:
  version: 2
  build:
    jobs:
      - build
