version: 2
jobs:
  build:
    working_directory: ~/wayback-discover-diff
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            # Even though Flask is included in setup.py, I get error:
            # error: The 'Flask' distribution was not found and is required by wayback-discover-diff
            # This fixes that.
            pip install Flask
            python setup.py develop
            # Even though pytest, mock & pylint are defined in setup.py, they
            # are not installed. This fixes that.
            pip install pytest mock pylint
      - run:
          name: Tests
          command: |
            . venv/bin/activate
            pytest tests
      - run:
          name: Code linting
          command: |
            . venv/bin/activate
            pylint wayback_discover_diff

workflows:
  version: 2
  build:
    jobs:
      - build
